# This file was generated by GoReleaser. DO NOT EDIT.
cask "iroh-tunnel" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "4bc0782f68a45d74675e63884e643d9775b0bd790cd6c57bf691261d9d841ec0"
      url "https://github.com/naicoi92/iroh-tunnel/releases/download/v#{version}/iroh-tunnel-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "iroh-tunnel"
  desc "P2P port-forwarding tunnel (TCP/UDP) via Iroh."
  homepage "https://github.com/naicoi92/iroh-tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iroh-tunnel"

  postflight do
    if OS.mac?
      # Remove the quarantine attribute so macOS Gatekeeper does not
      # block the unsigned (cosign is deferred) command-line binary.
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/iroh-tunnel"]

      # Install the `it` convenience alias: symlink it -> iroh-tunnel in
      # Homebrew's bin dir. `postflight` runs AFTER the cask's `binary`
      # stanza has linked iroh-tunnel into #{HOMEBREW_PREFIX}/bin, so the
      # target already exists and a relative symlink resolves on PATH.
      # (Creating the link inside staged_path does NOT work — cask only
      # links artifacts declared in a `binary` stanza, so an in-staged
      # symlink would be silently dropped.) `-sf` so `brew upgrade`
      # recreates the link cleanly.
      system_command "/bin/ln",
        args: ["-sf", "iroh-tunnel", "#{HOMEBREW_PREFIX}/bin/it"]
    end
  end

  # No zap stanza required

end
