# This file was generated by GoReleaser. DO NOT EDIT.
cask "iroh-tunnel" do
  version "0.1.0-rc.1"

  on_macos do
    on_arm do
      sha256 "f61e0f21808fc797a277933f7e4394e10bd308959473ff5e5cb214add79c79c8"
      url "https://github.com/naicoi92/iroh-tunnel/releases/download/v#{version}/iroh-tunnel-#{version}-darwin-arm64.tar.gz"
    end
  end

  name "iroh-tunnel"
  desc "P2P port-forwarding tunnel (TCP/UDP) via Iroh."
  homepage "https://github.com/naicoi92/iroh-tunnel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iroh-tunnel"

  postflight do
    if OS.mac?
      # Remove the quarantine attribute so macOS Gatekeeper does not
      # block the unsigned (cosign is deferred) command-line binary.
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/iroh-tunnel"]
    end
  end

  # No zap stanza required

end
